//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_StorePhone3.Models.db
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public user()
        {
            this.comments = new HashSet<comment>();
            this.orders = new HashSet<order>();
            this.roleusers = new HashSet<roleuser>();
        }

        public int id { get; set; }
        [Required(ErrorMessage = "Enter Username")]
        [Display(Name = "UserName")]
        public string username { get; set; }
        [Required(ErrorMessage = "Enter Password")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [MinLength(6, ErrorMessage = "Minimum 6 characters required")]
        public string password { get; set; }
        [Required(ErrorMessage = "Enter Email")]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }
        [Required(ErrorMessage = "Enter FullName")]
        [Display(Name = "FullName")]
        public string name { get; set; }
        public int activeFlag { get; set; }
        public System.DateTime createDate { get; set; }
        public System.DateTime updateDate { get; set; }
    
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<roleuser> roleusers { get; set; }
    }
}
